# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - sensorndf

on:
  push:
    branches:
      - main
      - feature/minor-improvements
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          
      #- name: Install dependencies
      #  run: pip install -r ./src/api/requirements.txt
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            ./api/*

      - name: Upload helper code for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: helper-code
          path: |
            ./src/utils/*
            ./src/predictor/*
            ./src/config.py

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: Download utils from build job
        uses: actions/download-artifact@v2
        with:
          name: helper-code
          path: ./src/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      
      - name: Step Env var
        run: echo "Setting env to production"
        env:
          DEPLOY_ENV: "production"

      - name: Display env vars
        run: env       
         
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'sensorndf'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FEA738BF5CF24C358AE2D74C70509BE4 }}
